# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.fancycar.com:
  peer0.didi.fancycar.com:
  peer1.didi.fancycar.com:
  peer0.guazi.fancycar.com:
  peer1.guazi.fancycar.com:

networks:
  byfn:

services:

  orderer.fancycar.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.fancycar.com
    container_name: orderer.fancycar.com
    networks:
      - byfn

  peer0.didi.fancycar.com:
    container_name: peer0.didi.fancycar.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.didi.fancycar.com
    networks:
      - byfn

  peer1.didi.fancycar.com:
    container_name: peer1.didi.fancycar.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.didi.fancycar.com
    networks:
      - byfn

  peer0.guazi.fancycar.com:
    container_name: peer0.guazi.fancycar.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.guazi.fancycar.com
    networks:
      - byfn

  peer1.guazi.fancycar.com:
    container_name: peer1.guazi.fancycar.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.guazi.fancycar.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.2.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.didi.fancycar.com:7051
      - CORE_PEER_LOCALMSPID=DidiMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/didi.fancycar.com/peers/peer0.didi.fancycar.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/didi.fancycar.com/peers/peer0.didi.fancycar.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/didi.fancycar.com/peers/peer0.didi.fancycar.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/didi.fancycar.com/users/Admin@didi.fancycar.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.fancycar.com
      - peer0.didi.fancycar.com
      - peer1.didi.fancycar.com
      - peer0.guazi.fancycar.com
      - peer1.guazi.fancycar.com
    networks:
      - byfn
