# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.fancycar.com:
    container_name: orderer.fancycar.com
    image: hyperledger/fabric-orderer:1.2.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
    - ../crypto-config/ordererOrganizations/fancycar.com/orderers/orderer.fancycar.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/fancycar.com/orderers/orderer.fancycar.com/tls/:/var/hyperledger/orderer/tls
    - orderer.fancycar.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.didi.fancycar.com:
    container_name: peer0.didi.fancycar.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.didi.fancycar.com
      - CORE_PEER_ADDRESS=peer0.didi.fancycar.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.didi.fancycar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.didi.fancycar.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=DidiMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=didicouchdb:5984
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/didi.fancycar.com/peers/peer0.didi.fancycar.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/didi.fancycar.com/peers/peer0.didi.fancycar.com/tls:/etc/hyperledger/fabric/tls
        - peer0.didi.fancycar.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.didi.fancycar.com:
    container_name: peer1.didi.fancycar.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.didi.fancycar.com
      - CORE_PEER_ADDRESS=peer1.didi.fancycar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.didi.fancycar.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.didi.fancycar.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=DidiMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/didi.fancycar.com/peers/peer1.didi.fancycar.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/didi.fancycar.com/peers/peer1.didi.fancycar.com/tls:/etc/hyperledger/fabric/tls
        - peer1.didi.fancycar.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
    # depends_on:
    #   - orderer.fancycar.com
      # - didicouchdb

  peer0.guazi.fancycar.com:
    container_name: peer0.guazi.fancycar.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.guazi.fancycar.com
      - CORE_PEER_ADDRESS=peer0.guazi.fancycar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.guazi.fancycar.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.guazi.fancycar.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=GuaziMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/guazi.fancycar.com/peers/peer0.guazi.fancycar.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/guazi.fancycar.com/peers/peer0.guazi.fancycar.com/tls:/etc/hyperledger/fabric/tls
        - peer0.guazi.fancycar.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
    # depends_on:
    #   - orderer.fancycar.com
      # - didicouchdb

  peer1.guazi.fancycar.com:
    container_name: peer1.guazi.fancycar.com
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.guazi.fancycar.com
      - CORE_PEER_ADDRESS=peer1.guazi.fancycar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.guazi.fancycar.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.guazi.fancycar.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=GuaziMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/guazi.fancycar.com/peers/peer1.guazi.fancycar.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/guazi.fancycar.com/peers/peer1.guazi.fancycar.com/tls:/etc/hyperledger/fabric/tls
        - peer1.guazi.fancycar.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
    # depends_on:
    #   - orderer.fancycar.com
      # - didicouchdb
